### PR TITLE
Move app to root directory

### PR DESCRIPTION
**Pull request by AndrewX192**
Move the app to the root directory, to assist with build automation

### CODE REVIEW

**Comment by eanderso** [comment]
What was the _need_ to move this to the root directory? I understand the desire, but this was an unnecessary change.

**Comment by AndrewX192** [comment]
I'm trying to get arcusandroid to work with travis-ci, which seems rather focused around having the project live in the root. Happy to revert/change it back or to something else if you'd prefer?

**Comment by eanderso** [comment]
No its fine; this has already been merged. I just wish I had seen this before that happened because this should be as simple as adding a `before_script: cd arcusApp` to the `.travis.yml`. 

Regardless, you'll most-likely want to also disable the unit tests or, preferably, comment out the ones that aren't passing and create an issue (or two) to come back and get those working. A quick sample (without any tests) `.travis.yml` (without switching project roots):
```
language: android
dist: trusty

script: ./gradlew assembleDebug

before_script: cd arcusApp

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    # The BuildTools version used by your project
    - build-tools-28.0.3

    # The SDK version used to compile your project
    - android-27

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
```

You could probably use that as a start but remove the `before_script: cd arcusApp` line since this should no longer be needed.

**Comment by AndrewX192** [comment]
(this is a bit off-topic, but I don't have your email...)

Do you think you'd be able to enable travis-ci for arcusandroid (with the config you provided) and arcusplatform (with the config that's already there)?

arcusplatform is already passing tests, but it needs a time extension to complete the build in a timely manner.

**Comment by eanderso** [comment]
I've sent an email to you. Let me know if nothing comes through.

**Pull request merged**
